apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: caderno

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: caderno

# para apontar para uma SHA específica:
#   kustomize edit set image ghcr.io/alexsandroaf/projeto-caderno-nr1:<sha>
images:
  - name: ghcr.io/alexsandroaf/projeto-caderno-nr1
    newTag: latest
